# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 104

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  MaxSlashes: 0

Style/TrailingComma:
  EnforcedStyleForMultiline: comma
